# Generated by Django 2.2.4 on 2019-08-30 21:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localization', models.CharField(choices=[('warsaw', 'Warszawa'), ('wroclaw', 'Wrocław'), ('poznan', 'Poznań'), ('gdansk', 'Gdańsk')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_thing', models.CharField(choices=[('clothes-to-use', 'clothes-to-use'), ('clothes-useless', 'clothes-useless'), ('toys', 'toys'), ('books', 'books'), ('other', 'other')], max_length=15)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('localization', models.CharField(choices=[('warsaw', 'Warszawa'), ('wroclaw', 'Wrocław'), ('poznan', 'Poznań'), ('gdansk', 'Gdańsk')], max_length=7)),
                ('for_who', models.CharField(choices=[('children', 'children'), ('mothers', 'mothers'), ('homeless', 'homeless'), ('disabled', 'disabled'), ('old', 'old')], max_length=8)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.TextField(max_length=7)),
                ('phone_number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
